//Vistas clientes
CREATE OR REPLACE VIEW VISTA_CLIENTES AS
SELECT 
    ID_CLIENTE,
    NOMBRE || ' ' || APELLIDO AS NOMBRE_COMPLETO,
    EMAIL,
    TELEFONO,
    DIRECCION
FROM CLIENTES;

//Vistas productos detalle
CREATE OR REPLACE VIEW VISTA_PRODUCTOS_DETALLE AS
SELECT 
    P.ID_PRODUCTO,
    P.NOMBRE AS NOMBRE_PRODUCTO,
    P.DESCRIPCION,
    P.PRECIO,
    C.NOMBRE_CATEGORIA,
    PR.NOMBRE AS NOMBRE_PROVEEDOR
FROM PRODUCTOS P
LEFT JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
LEFT JOIN PROVEEDORES PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR;

//Vistas ordenes clientes
CREATE OR REPLACE VIEW VISTA_ORDENES_CLIENTES AS
SELECT 
    O.ID_ORDEN,
    C.NOMBRE || ' ' || C.APELLIDO AS CLIENTE,
    O.FECHA,
    O.TOTAL
FROM ORDENES O
INNER JOIN CLIENTES C ON O.ID_CLIENTE = C.ID_CLIENTE;

//Vistas carritos
CREATE OR REPLACE VIEW VISTA_CARRITOS AS
SELECT 
    CP.ID_CARRITO,
    C.NOMBRE || ' ' || C.APELLIDO AS CLIENTE,
    P.NOMBRE AS PRODUCTO,
    CP.CANTIDAD,
    P.PRECIO,
    CP.CANTIDAD * P.PRECIO AS SUBTOTAL
FROM CARRITO_PRODUCTO CP
INNER JOIN PRODUCTOS P ON CP.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN CARRITO CARR ON CP.ID_CARRITO = CARR.ID_CARRITO
INNER JOIN CLIENTES C ON CARR.ID_CLIENTE = C.ID_CLIENTE;

//Vistas inventario
CREATE OR REPLACE VIEW VISTA_INVENTARIO AS
SELECT 
    S.NOMBRE AS SUCURSAL,
    P.NOMBRE AS PRODUCTO,
    I.CANTIDAD,
    I.ULTIMA_ACTUALIZACION
FROM INVENTARIO I
INNER JOIN SUCURSALES S ON I.ID_SUCURSAL = S.ID_SUCURSAL
INNER JOIN PRODUCTOS P ON I.ID_PRODUCTO = P.ID_PRODUCTO;

//Vistas ventas empleados 
CREATE OR REPLACE VIEW VISTA_VENTAS_EMPLEADOS AS
SELECT 
    E.ID_EMPLEADO,
    E.NOMBRE || ' ' || E.APELLIDO AS EMPLEADO,
    SUM(O.TOTAL) AS TOTAL_VENTAS
FROM ORDENES O
INNER JOIN EMPLEADOS E ON O.ID_EMPLEADO = E.ID_EMPLEADO
GROUP BY E.ID_EMPLEADO, E.NOMBRE, E.APELLIDO;

//Vistas envios pendientes
CREATE OR REPLACE VIEW VISTA_ENVIOS_PENDIENTES AS
SELECT 
    E.ID_ENVIO,
    O.ID_ORDEN,
    C.NOMBRE || ' ' || C.APELLIDO AS CLIENTE,
    E.ESTADO,
    E.FECHA_ENVIO,
    E.FECHA_ENTREGA_ESTIMADA,
    E.DIRECCION_ENVIO
FROM ENVIOS E
INNER JOIN ORDENES O ON E.ID_ORDEN = O.ID_ORDEN
INNER JOIN CLIENTES C ON O.ID_CLIENTE = C.ID_CLIENTE
WHERE E.ESTADO != 'Entregado';

//Vistas productos mas vendidos
CREATE OR REPLACE VIEW VISTA_PRODUCTOS_MAS_VENDIDOS AS
SELECT 
    P.NOMBRE AS PRODUCTO,
    SUM(OP.CANTIDAD) AS TOTAL_VENDIDO
FROM ORDENES_PRODUCTOS OP
INNER JOIN PRODUCTOS P ON OP.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY P.NOMBRE
ORDER BY TOTAL_VENDIDO DESC;

//Vistas ordenes detalle
CREATE OR REPLACE VIEW VISTA_ORDENES_DETALLE AS
SELECT 
    O.ID_ORDEN,
    C.NOMBRE || ' ' || C.APELLIDO AS CLIENTE,
    P.NOMBRE AS PRODUCTO,
    OP.CANTIDAD,
    P.PRECIO,
    OP.CANTIDAD * P.PRECIO AS SUBTOTAL
FROM ORDENES O
INNER JOIN ORDENES_PRODUCTOS OP ON O.ID_ORDEN = OP.ID_ORDEN
INNER JOIN PRODUCTOS P ON OP.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN CLIENTES C ON O.ID_CLIENTE = C.ID_CLIENTE;

//Vistas de todos los inventarios
CREATE OR REPLACE VIEW VISTA_INVENTARIO_GLOBAL AS
SELECT 
    P.NOMBRE AS PRODUCTO,
    SUM(I.CANTIDAD) AS TOTAL_EN_EXISTENCIA
FROM INVENTARIO I
INNER JOIN PRODUCTOS P ON I.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY P.NOMBRE;
