-- Creación de la tabla INVENTARIO
CREATE TABLE INVENTARIO (
    ID_INVENTARIO NUMBER PRIMARY KEY, 
    ID_SUCURSAL NUMBER,              
    ID_PRODUCTO NUMBER,              
    CANTIDAD NUMBER NOT NULL,       
    ULTIMA_ACTUALIZACION DATE DEFAULT SYSDATE, 
    CONSTRAINT FK_ID_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL),
    CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);



-- Creación de la tabla PROVEEDORES
CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR NUMBER PRIMARY KEY, 
    NOMBRE VARCHAR2(100) NOT NULL,  
    CONTACTO VARCHAR2(100),         
    TELEFONO VARCHAR2(15),         
    DIRECCION VARCHAR2(200)        
);




-- Creación de la tabla SUCURSALES
CREATE TABLE SUCURSALES (
    ID_SUCURSAL NUMBER PRIMARY KEY, 
    NOMBRE VARCHAR2(100) NOT NULL,  
    DIRECCION VARCHAR2(200) NOT NULL, 
    TELEFONO VARCHAR2(15)            
);



-- Creación de la tabla ENVIOS
CREATE TABLE ENVIOS (
    ID_ENVIO NUMBER PRIMARY KEY,             
    ID_ORDEN NUMBER NOT NULL,                  
    ESTADO VARCHAR2(50) NOT NULL,              
    FECHA_ENVIO DATE DEFAULT SYSDATE,         
    FECHA_ENTREGA_ESTIMADA DATE,              
    DIRECCION_ENVIO VARCHAR2(200) NOT NULL,    
    CONSTRAINT FK_ID_ORDEN FOREIGN KEY (ID_ORDEN) REFERENCES ORDENES(ID_ORDEN) 
);


-- Creación de la tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO NUMBER PRIMARY KEY,       
    NOMBRE VARCHAR2(100) NOT NULL,       
    APELLIDO VARCHAR2(100) NOT NULL,      
    TELEFONO VARCHAR2(15),               
    ID_SUCURSAL NUMBER NOT NULL,         
    CONSTRAINT FK_ID_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL) 

);



-- Creación de la tabla CARRITO_PRODUCTO
CREATE TABLE CARRITO_PRODUCTO (
    ID_CARRITO NUMBER,               
    ID_PRODUCTO NUMBER,              
    CANTIDAD NUMBER NOT NULL,        
    CONSTRAINT PK_CARRITO_PRODUCTO PRIMARY KEY (ID_CARRITO, ID_PRODUCTO), 
    CONSTRAINT FK_ID_CARRITO FOREIGN KEY (ID_CARRITO) REFERENCES CARRITO(ID_CARRITO), 
    CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO) 
);

